
pipeline:
  type: Ingest

  location_id: "nwtc"
  dataset_name: "z01"
  qualifier: "lidar"
  # temporal: "10min"
  data_level: "a1"

dataset_definition:  # Describes the dataset that will be produced
  attributes:
    title: Lidar Ingest for Halo Lidar
    description: ingest of data from Halo Lidar at NREL Flatirons Campus 
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: NREL
    code_url: https://github.com/clansing/tsdat/releases/tag/1.0
    location_meaning: NREL Flatirons Campus
    # location_id: NWTC_4.0
    # instrument_id: WLS7-224
    # data_level: b1

  dimensions:
    time:
        length: unlimited
    
    range_gate:
        length: 720

  variables:

    time:
      input:
        name: Timestamp
        # converter:
        #   classname: tsdat.utils.converters.DecimalTimeConverter
        #   parameters:
        #     timezone: UTC
        #     unit: 'H'
            # time_format: "%Y/%m/%d %H:%M"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    range_gate:
      input:
        name: range_gate
      dims: [range_gate]
      type: int
      attrs:
        long_name: Range gate

    distance:
      input:
        name: distance
      dims: [range_gate]
      type: int
      attrs:
        long_name: Distance LOS measurement is taken from Lidar
        units: m
    
    azimuth:
      dims: [time]
      type: float
      input:
        name: Azimuth (degrees)
      attrs:
        long_name: Azimuth
        units: deg

    elevation:
      dims: [time]
      type: float
      input:
        name: Elevation (degrees)
      attrs:
        long_name: Elevation
        units: deg

    pitch:
      dims: [time]
      type: float
      input:
        name: Pitch (degrees)
      attrs:
        long_name: Pitch
        units: deg

    roll:
      dims: [time]
      type: float
      input:
        name: Roll (degrees)
      attrs:
        long_name: Roll
        units: deg
    
    doppler:
      dims: [time, range_gate]
      type: float
      input:
        name: Doppler
      attrs:
        long_name: Doppler
        units: m/s
        valid_delta: 1

    intensity:
      dims: [time, range_gate]
      type: float
      attrs:
        long_name: Intensity
        units: mag
      input:
        name: Intensity
    
    
#-----------------------------------------------------------------
quality_management:

  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  manage_valid_delta:
    checker:
      classname: tsdat.qc.checkers.CheckValidDelta
      parameters:
        dim: time  # specifies the dimension over which to compute the delta
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 2
          assessment: "Indeterminate"
          meaning: "Difference between current and previous values exceeds valid_delta."
    variables:
      - doppler

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS